runtime: python310
entrypoint: gunicorn Management.wsgi:application

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "Management.settings"
  SECRET_KEY: "a-j9a-q7b0zl-^4090s)gnkh%$@i^0gqnn&g-w_pxdgfsh8xb3"
  DEBUG: "False"
  ALLOWED_HOSTS: ".appspot.com"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
