# Generated by Django 4.2.19 on 2025-05-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ISPManagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wifiplan",
            name="wifiprovider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ISPManagement.wifiproviders",
            ),
        ),
    ]
