# Generated by Django 4.2.19 on 2025-05-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ISPManagement", "0001_initial"),
        ("Captive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ISPManagement.wifiplan"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="providers",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="ISPManagement.wifiproviders",
            ),
        ),
        migrations.AddField(
            model_name="subscribers",
            name="access_code",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ISPManagement.accesscode",
            ),
        ),
        migrations.AddField(
            model_name="subscribers",
            name="wifi_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ISPManagement.wifiplan",
            ),
        ),
        migrations.AddField(
            model_name="subscribers",
            name="wifi_provider",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="ISPManagement.wifiproviders",
            ),
        ),
    ]
