# Generated by Django 4.2.19 on 2025-05-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Captive", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="providers",
        ),
    ]
