# Generated by Django 4.2.19 on 2025-05-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ISPManagement", "0002_wifiplan_wifiprovider"),
        ("Captive", "0003_remove_transaction_plan_remove_transaction_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ISPManagement.wifiplan",
            ),
        ),
    ]
