# Generated by Django 4.2.19 on 2025-05-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Captive", "0004_transaction_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribers",
            name="last_payment_amount",
        ),
        migrations.RemoveField(
            model_name="subscribers",
            name="last_payment_date",
        ),
        migrations.RemoveField(
            model_name="subscribers",
            name="password",
        ),
        migrations.RemoveField(
            model_name="subscribers",
            name="static_ip",
        ),
        migrations.RemoveField(
            model_name="subscribers",
            name="username",
        ),
    ]
